export const SITE = {
  name: "Mentes que Florecen",
  tagline: "Campaña gratuita de salud mental",
  eventDate: "Sábado 19 de septiembre, 2026",
  venue: "Municipalidad Provincial de Arequipa",
  mapsUrl: "https://maps.app.goo.gl/HxwwNPUnCyoZ6MTb9",
  mapsEmbedUrl: "https://www.google.com/maps?q=-16.3994657,-71.5368586&z=17&output=embed",
  timezone: "America/Lima",
  capacityPerSlot: 10,
  minAge: 14,
  maxAge: 29,
  helpline: "Línea 113, opción 5 — salud mental, 24 h.",
  emergency: "Emergencias: 106.",
  contactEmail: "mentesqueflorecen@residuosqueeducan.org.pe",
  website: "residuosqueeducan.org.pe",
} as const;
